LeggedRobotCfg:
  init_state:
    # target angles [rad] when action = 0.0
    default_joint_angle:
      L_CROTCH_R: 0.0
      L_CROTCH_P: 0.0 
      L_KNEE_P: 0.0
      L_TOE_P: 0.0
      R_CROTCH_R: 0.0
      R_CROTCH_P: 0.0
      R_KNEE_P: 0.0
      R_TOE_P: 0.0

  control:
    stiffness:
      L_CROTCH_R: 25.0
      L_CROTCH_P: 25.0 
      L_KNEE_P: 25.0
      L_TOE_P: 15.0
      R_CROTCH_R: 25.0
      R_CROTCH_P: 25.0
      R_KNEE_P: 25.0
      R_TOE_P: 15.0
    damping:
      L_CROTCH_R: 2.5
      L_CROTCH_P: 2.5  
      L_KNEE_P: 2.5
      L_TOE_P: 1.5
      R_CROTCH_R: 2.5
      R_CROTCH_P: 2.5
      R_KNEE_P: 2.5
      R_TOE_P: 1.5

    action_scale: 0.5
    decimation: 10.0

  normalization:
    clip_scales:
      clip_observations: 100.0
      clip_actions: 100.0
    obs_scales:
      lin_vel: 2
      ang_vel: 1
      dof_pos: 1
      dof_vel: 0.05
      quat: 1

  size:
    actions_size: 9
    observations_size: 46
